ColdControl/ColdControl/urls.py
# As URLs principais do projeto Django.
from django.contrib import admin
from django.urls import include, path

# Essa é uma lista onde você define quais caminhos o Django deve "escutar" e 
# o que fazer quando cada caminho for acessado.
urlpatterns = [
    path('camara/', include("camaraView.urls")),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

ColdControl/accounts/urls.py
# Esse código configura as rotas (URLs) de uma aplicação no Django.
from django.urls import path

from . import views

# Essa lista define as rotas específicas para a aplicação e mapeia cada URL para uma view.
app_name = "accounts"
urlpatterns = [
    path("", views.login, name="login"),
    path("signUP/", views.signUP, name="signUP"),
    path("validateUser/", views.validateUser, name="validateUser"),
    path("createNewUser/", views.createNewUser, name="createNewUser"),
]

ColdControl/camaraView/urls.py
# Esse código configura as rotas (URLs) de uma aplicação no Django.
from django.urls import path

from . import views

# Essa lista define as rotas específicas para a aplicação e mapeia cada URL para uma view.
app_name = "camaraView"
urlpatterns = [
    path("", views.home, name="home")
]

ColdControl/accounts/models.py
#                                   Model
# É responsável por representar a estrutura e a lógica de dados da aplicação. 
# Ele define como os dados serão acessados, manipulados e armazenados, 
# assim como faz a interação com o banco de dados.
# ==========================================================================================================
# O Django utiliza o ORM (Object-Relational Mapping), 
# que permite que você utilize classes e objetos no Python para mapear 
# as tabelas do banco de dados, fazendo a criação, consulta, atualização e 
# exclusão de dados com mais segurança e facilidade.
# ==========================================================================================================
# Isso permite que você trabalhe com banco de dados relacionais sem ter a necessidade de lidar com SQL diretamente. 
# Além disso, você pode trabalhar com vários sistemas de 
# gerenciamento de banco de dados relacionais utilizando a mesma sintaxe e API.

from django.db import models

class User(models.Model):
    id_user = models.AutoField(primary_key=True, verbose_name="User Id")
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def showCreationDate(self):
        return self.created_at

ColdControl/camaraView/models.py
from django.db import models

class Product(models.Model):
    product_name = models.CharField(
        max_length=100,
        verbose_name="Nome do Produto",
        help_text="Nome completo do produto."
    )
    category = models.CharField(
        max_length=100,
        verbose_name="Categoria",
        help_text="Categoria do produto (ex.: bombom, copinho, pote)."
    )
    qtty = models.PositiveIntegerField(
        verbose_name="Quantidade",
        help_text="Quantidade atual do produto em estoque."
    )

    def __str__(self):
        return f"{self.product_name} ({self.category}) - {self.qtty} unidades"

    # Adicionada para personalizar o nome e a ordem padrão dos registros.
    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"
        ordering = ['product_name']

ColdControl/accounts/views.py
#                                               View
# ==========================================================================================================
# É responsável por processar as solicitações HTTP do usuário e retornar as respostas desse processamento. 
# As views são funções e classes que lidam com a lógica de negócios da aplicação, 
# sendo projetadas para serem reutilizáveis e utilizadas em diferentes aplicações de um mesmo projeto.
# ==========================================================================================================
# As views recebem as solicitações do usuário e consultam ou manipulam os dados nos modelos para retornar uma
#  resposta HTTP adequada à solicitação, como uma página HTML, um arquivo JSON, um arquivo de imagem, 
# dentre outros diversos formatos.
# ==========================================================================================================


from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth import authenticate, login as auth_login
from django.contrib import messages
from django.http import HttpResponse

from .models import User

# Quero que uma view login, vai receber email e senha
# Se corresponder redirecionar para página de home
# Senão retornar um alert dizendo email ou senha incorretos

def login(request):
    return render(request, "accounts/login.html")

def validateUser(request):
    if request.method == 'POST':
        email = request.POST.get('fEmail')
        password = request.POST.get('fPassword')
        print(email, password)

        

        if isUser(email, password):
            user = authenticate(request, email=email, password=password)

            # Essa função serve para atribuir request.user ao usuário autenticado
            # Você pode usar request.user em qualquer view, template ou middleware 
            # para personalizar a experiência, verificar permissões ou exibir informações específicas 
            # do usuário.
            auth_login(request, user)
            return redirect('camaraView:home')
        else:
            messages.error(request, 'Email ou senha incorretos')
            redirect('accounts:login')
    
    return redirect('accounts:login')

def isUser(email, password):
    if User.objects.filter(email=email, password=password):
        return True
    return False

# Quero ter uma view de signUp
def signUP(request):
    template = loader.get_template("accounts/signup.html")
    return render(request, "accounts/signup.html")

def createNewUser(request):
    if request.method == 'POST':
        name = request.POST.get('fName')
        # Ele faz a requisição pelo name das tags html!
        email = request.POST.get('fEmail')
        password = request.POST.get('fPassword')
    
        # Verifica se todos os parametros forma enviados
        if not all ([name, email, password]):
            messages.error(request, 'Please fill out all the fields!')
            return redirect('accounts:signUP')
        
        # Verifica se email já está no bd
        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email already used')
            return redirect('accounts:signUP')

        # instancia objeto a classe user, com isso salva no bd
        newUser = User(name=name, email=email, password=password)
        newUser.save()

        messages.success(request, 'New account created, sign In to have access')
        return redirect('accounts:login')
   
    return redirect('accounts:signUP')

ColdControl/camaraView/views.py
from django.shortcuts import render
from .models import Product
# Create your views here.
def home(request):
    products = Product.objects.all()
    return render(request, "camaraView/home.html", {"products":products})

ColdControl/accounts/templates/accounts/login.html
{% extends "./template.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white text-center">
                    <h2 class="h4 mb-0">Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:validateUser' %}" method="POST">
                        {% csrf_token %}
                        
                        <!-- Email -->
                        <div class="form-group mb-4">
                            <label for="fEmail" class="form-label">Email</label>
                            <input type="email" id="fEmail" class="form-control" placeholder="Enter your email" name="fEmail" required>
                        </div>

                        <!-- Password -->
                        <div class="form-group mb-4">
                            <label for="fPassword" class="form-label">Password</label>
                            <input type="password" id="fPassword" class="form-control" placeholder="Enter your password" name="fPassword" required>
                        </div>

                        <!-- Submit Button -->
                        <div class="form-group mb-4">
                            <button type="submit" class="btn btn-primary btn-block" style="margin-left: 150px">Login</button>
                            <br>
                                <span>
                                    Don't have an account? 
                                    <a href="{% url 'accounts:signUP' %}" style="decoration-text: none">
                                        Sign up
                                    </a>
                                </span>
                        </div>


                    </form>

                    {% if messages %}
                    <br>
                        {% for message in messages %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



ColdControl/accounts/templates/accounts/signup.html
{% extends "./template.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white text-center">
                    <h2 class="h4 mb-0">Sign Up</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:createNewUser' %}" method="POST">
                        {% csrf_token %}
                        <!-- Email -->
                        <div class="form-group mb-4">
                            <label for="fEmail" class="form-label">Email</label>
                            <input type="email" id="fEmail" class="form-control" placeholder="Enter your email" name="fEmail" required>
                        </div>

                        <!-- Name -->
                        <div class="form-group mb-4">
                            <label for="fName" class="form-label">Name</label>
                            <input type="text" id="fName" class="form-control" placeholder="Enter your name" name="fName" required>
                        </div>

                        <!-- Password -->
                        <div class="form-group mb-4">
                            <label for="fPassword" class="form-label">Password</label>
                            <input type="password" id="fPassword" class="form-control" placeholder="Enter your password" name="fPassword" required>
                        </div>

                        <!-- Submit Button -->
                        <div class="form-group mb-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                        </div>
                    </form>

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ColdControl/accounts/templates/accounts/template.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Cold Control</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    </head>
    <body>

        {% block content %}{% endblock content %}

        <script src="{% static 'bootstrap/js/bootstrap.js' %}" async defer></script>
    </body>
</html>

ColdControl/camaraView/templates/camaraView/home.html
{% extends "./template.html" %}
{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Lista de Produtos</h1>

    <!-- Tabela para exibir os produtos -->
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col">Nome do Produto</th>
                <th scope="col">Categoria</th>
                <th scope="col">Quantidade</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.product_name }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.qtty }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}





ColdControl/camaraView/templates/camaraView/template.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">    </head>
    <body>
    
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- Ícone à esquerda -->
                <a class="navbar-brand" href="#">
                   <span>Cold Control</span>
                </a>
                
                <!-- Botão para colapsar em telas menores -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <!-- Conteúdo da navbar -->
                <div class="collapse navbar-collapse" id="navbarContent">
                    <!-- Barra de busca à direita -->
                    <form class="d-flex ms-auto">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        

        {% block content %}{% endblock content %}
        
        <script src="{% static 'bootstrap/js/bootstrap.js' %}" async defer></script>
    </body>
</html>